spring:
  application:
    name: box-gateway
  cloud:
    gateway:
      routes:
        - id: box-authcenter
          uri: lb://box-authcenter
          predicates:
            - Path=/oauth/**

server:
  port: 8888

box:
  gateway:
    shouldSkipUrls:
      - /oauth/**
      - /sso/**
      - /home/**
      - /portal/commentlist/**
      - /order/paySuccess/**
      - /pms/**
      - /static/qrcode/**